name: Node.js CI/CD Pipeline

# Define quais eventos disparam o pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Etapa de Integração Contínua (CI)
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20 # Versão do Node.js que você deseja usar
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci

    - name: Executar testes automatizados
      run: npm test

  # Etapa de Entrega Contínua (CD) - Só roda se o teste passar
  deploy-simulation:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Simular Deploy / Empacotar Artefato
      run: |
        echo "Preparando arquivos para produção..."
        mkdir build
        cp -r src package.json package-lock.json build/
        echo "Deploy simulado com sucesso!"

  # -------------------------------------------------------
  # ETAPA 2: CD (Entrega Contínua) - Só roda em Push na Main se o CI passar (não testei)
  # -------------------------------------------------------
  # deploy-to-render:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  #   steps:
  #   - name: Disparar Deploy no Render via Webhook
  #     run: |
  #       echo "Iniciando o deploy no Render..."
  #       curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
  #       echo "Deploy solicitado com sucesso!"